language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --all-features --verbose
  - cargo test --all-features --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
after_success:
- test $TRAVIS_BRANCH = "main" && ./ci/docs.sh